"""Synthetic custody and native-pipe contracts; no experimental source opens."""

from contextlib import ExitStack
import hashlib
import os
from pathlib import Path
import stat
import subprocess
import sys
import tempfile
from types import SimpleNamespace
import unittest
from unittest import mock

from snbi_fragmentation import study2a_streaming as streaming


def metadata(size, inode):
    return SimpleNamespace(st_dev=1, st_ino=inode, st_mode=stat.S_IFREG | 0o444,
                           st_nlink=1, st_size=size, st_mtime_ns=1, st_ctime_ns=1)


def pipe_record():
    return {"native_bytes_received": 0, "decoder_stderr_bytes": 0,
            "decoder_exit_code": None}


class SyntheticAuthentication:
    """Replace all custody operations with generated bytes and metadata."""

    def __init__(self, bad_hash=None, bad_size=None):
        self.stack = ExitStack()
        self.records = {
            101 + index: metadata(spec.size_bytes, 1001 + index)
            for index, spec in enumerate(streaming.SOURCES.values())
        }
        self.bad_hash = bad_hash
        self.bad_size = bad_size

    def __enter__(self):
        patches = self.stack.enter_context
        self.open = patches(mock.patch.object(streaming, "_open_source", side_effect=[101, 102]))
        self.close = patches(mock.patch.object(streaming.os, "close"))
        self.seek = patches(mock.patch.object(streaming.os, "lseek"))
        sizes = [s.size_bytes for s in streaming.SOURCES.values()]
        if self.bad_size is not None:
            self.records[101 + self.bad_size].st_size -= 1
        self.fstat = patches(mock.patch.object(streaming.os, "fstat",
                                             side_effect=lambda fd: self.records[fd]))
        self.stat = patches(mock.patch.object(streaming, "_stat_source",
                                            side_effect=lambda spec: self.records[101 + streaming.SOURCE_ORDER.index(spec.source_id)]))
        # Contents are wholly synthetic. Hash objects stand in for the two
        # historical digests so no experimental bytes or paths are required.
        self.read = patches(mock.patch.object(streaming.os, "read", side_effect=[
            bytes(sizes[0]), b"", bytes(sizes[1]), b"",
        ]))
        hashes = [s.sha256 for s in streaming.SOURCES.values()]
        if self.bad_hash is not None:
            hashes[self.bad_hash] = "0" * 64
        digests = [mock.Mock(hexdigest=mock.Mock(return_value=value)) for value in hashes]
        self.hash = patches(mock.patch.object(streaming.hashlib, "sha256", side_effect=digests))
        return self

    def restore_hash(self):
        # Keep a separate implementation for emitted synthetic native frames.
        self.hash.side_effect = lambda value=b"": hashlib.new("sha256", value)

    def __exit__(self, *arguments):
        return self.stack.__exit__(*arguments)


def fake_process(running=False):
    process = mock.Mock()
    process.poll.return_value = None if running else 0
    process.returncode = 0
    process.wait.return_value = 0
    return process


class StreamingCustodyTests(unittest.TestCase):
    def test_constructor_is_inert_and_unknown_modes_fail_before_touch(self):
        with mock.patch.object(streaming.os, "open") as opened:
            reader = streaming.AuthenticatedSources("legacy")
            self.assertEqual(reader.audit["state"], "NOT_ENTERED")
            for mode in ("training", "LEGACY", "", None, True):
                with self.assertRaisesRegex(streaming.StreamingContractError, "MODE"):
                    streaming.AuthenticatedSources(mode)
            opened.assert_not_called()

    def test_unknown_ids_and_paths_fail_before_touch(self):
        with mock.patch.object(streaming.os, "open") as opened:
            reader = streaming.AuthenticatedSources("full")
            for source in ("ESM1", "ESM2", "ESM4", "ESM5", "../ESM3", streaming.SOURCES["ESM3"].path, None):
                with self.assertRaisesRegex(streaming.StreamingContractError, "SOURCE_NOT_AUTHORIZED"):
                    reader.iter_frames(source)
            opened.assert_not_called()

    def test_known_source_requires_entered_authenticated_reader(self):
        reader = streaming.AuthenticatedSources("full")
        with mock.patch.object(streaming, "_open_source") as opened:
            with self.assertRaisesRegex(streaming.StreamingContractError, "NOT_AUTHENTICATED"):
                reader.iter_frames("ESM3")
            opened.assert_not_called()

    def test_both_hashes_complete_before_any_decoder_launch(self):
        audit = {}
        with SyntheticAuthentication() as fixture, mock.patch.object(streaming.subprocess, "Popen") as launch:
            with streaming.AuthenticatedSources("full", audit) as reader:
                self.assertTrue(audit["both_sources_authenticated"])
                self.assertEqual(audit["source_auth_opens"], 2)
                self.assertEqual(audit["source_auth_bytes_read"], 7709238)
                self.assertEqual(fixture.hash.call_count, 2)
                launch.assert_not_called()
            self.assertEqual(fixture.close.call_args_list, [mock.call(101), mock.call(102)])
        self.assertEqual(audit["state"], "CLOSED_INCOMPLETE")

    def test_second_hash_failure_closes_both_without_decoding(self):
        audit = {}
        with SyntheticAuthentication(bad_hash=1) as fixture, mock.patch.object(streaming.subprocess, "Popen") as launch:
            with self.assertRaisesRegex(streaming.StreamingContractError, "HASH_MISMATCH"):
                with streaming.AuthenticatedSources("full", audit):
                    self.fail("bad custody must not enter")
            launch.assert_not_called()
            self.assertEqual(fixture.close.call_args_list, [mock.call(101), mock.call(102)])
        self.assertEqual(audit["source_auth_opens"], 2)
        self.assertEqual(audit["state"], "AUTHENTICATION_FAILED")

    def test_wrong_size_denies_before_source_content_read(self):
        with SyntheticAuthentication(bad_size=0) as fixture:
            with self.assertRaisesRegex(streaming.StreamingContractError, "SIZE_MISMATCH"):
                with streaming.AuthenticatedSources("legacy"):
                    self.fail("size mismatch")
            fixture.read.assert_not_called()
            fixture.close.assert_called_once_with(101)

    def test_metadata_mutation_after_auth_denies_before_decoder(self):
        with SyntheticAuthentication() as fixture, mock.patch.object(streaming.subprocess, "Popen") as launch:
            with streaming.AuthenticatedSources("full") as reader:
                fixture.records[101].st_mtime_ns += 1
                with self.assertRaisesRegex(streaming.StreamingContractError, "METADATA_CHANGED"):
                    next(reader.iter_frames("ESM3"))
                launch.assert_not_called()
                with self.assertRaisesRegex(streaming.StreamingContractError, "NOT_AUTHENTICATED"):
                    reader.iter_frames("ESM6")

    def test_historical_command_only_selects_frozen_fixtures(self):
        for source, indices in (("ESM3", (0, 73, 146, 219, 293)), ("ESM6", (0, 98, 197, 295, 394))):
            command = streaming.decoder_command(source, 99, "legacy")
            self.assertEqual(command[command.index("-i") + 1], "/proc/self/fd/99")
            self.assertEqual(command[command.index("-vf") + 1],
                             "select=" + "+".join(f"eq(n\\,{i})" for i in indices))
            self.assertEqual(command[command.index("-frames:v") + 1], "5")
            self.assertEqual(command[command.index("-pix_fmt") + 1], "yuv420p")
            self.assertIn("-noautorotate", command)
            self.assertNotIn(streaming.SOURCES[source].path, command)

    def test_full_command_requires_natural_eof_without_frame_truncation(self):
        command = streaming.decoder_command("ESM6", 17, "full")
        self.assertNotIn("-frames:v", command)
        self.assertNotIn("-vf", command)
        self.assertNotIn("-ss", command)
        self.assertNotIn("-s", command)
        self.assertEqual(command[-3:], ["-f", "rawvideo", "pipe:1"])

    def test_historical_frame_order_counters_one_use_and_clean_close(self):
        audit = {}
        process = fake_process()
        def payloads(_process, size, count, record, timeout):
            record["decoder_exit_code"] = 0
            for _ in range(count):
                record["native_bytes_received"] += size
                yield bytes(size)
        with SyntheticAuthentication() as fixture, mock.patch.object(streaming.subprocess, "Popen", return_value=process) as launch, mock.patch.object(streaming, "_native_frames", side_effect=payloads):
            with streaming.AuthenticatedSources("legacy", audit) as reader:
                fixture.restore_hash()
                for source in streaming.SOURCE_ORDER:
                    observed = [index for index, _, _ in reader.iter_frames(source)]
                    self.assertEqual(observed, list(streaming.SOURCES[source].historical_indices))
                    with self.assertRaisesRegex(streaming.StreamingContractError, "ALREADY_CONSUMED"):
                        reader.iter_frames(source)
                self.assertEqual(launch.call_count, 2)
                self.assertEqual(launch.call_args.kwargs["pass_fds"], (102,))
                self.assertTrue(launch.call_args.kwargs["close_fds"])
        self.assertEqual(audit["state"], "CLOSED_COMPLETE")
        self.assertEqual(audit["frames_emitted"], 10)
        self.assertEqual(audit["native_bytes_emitted"], 19545600)
        self.assertEqual(audit["historical_intermediate_frames_delivered"], 0)
        process.stdout.close.assert_called()
        process.stderr.close.assert_called()

    def test_consumer_exception_closes_decoder_and_preserves_partial_counts(self):
        audit = {}
        process = fake_process(running=True)
        def payloads(_process, size, count, record, timeout):
            for _ in range(count):
                yield bytes(size)
        with SyntheticAuthentication() as fixture, mock.patch.object(streaming.subprocess, "Popen", return_value=process), mock.patch.object(streaming, "_native_frames", side_effect=payloads):
            with self.assertRaisesRegex(RuntimeError, "detector stopped"):
                with streaming.AuthenticatedSources("legacy", audit) as reader:
                    fixture.restore_hash()
                    stream = reader.iter_frames("ESM3")
                    next(stream)
                    with self.assertRaisesRegex(streaming.StreamingContractError, "CONCURRENT"):
                        reader.iter_frames("ESM6")
                    raise RuntimeError("detector stopped")
            process.kill.assert_called_once()
            self.assertEqual(fixture.close.call_count, 2)
        self.assertEqual(audit["state"], "CLOSED_INCOMPLETE")
        self.assertEqual(audit["frames_emitted"], 1)
        self.assertEqual(audit["sources"]["ESM3"]["state"], "CONSUMER_STOPPED_BEFORE_EOF")

    def test_launch_failure_does_not_claim_a_decoder_or_frame(self):
        audit = {}
        with SyntheticAuthentication(), mock.patch.object(streaming.subprocess, "Popen", side_effect=OSError("synthetic")):
            with streaming.AuthenticatedSources("legacy", audit) as reader:
                with self.assertRaises(OSError):
                    next(reader.iter_frames("ESM3"))
        self.assertEqual(audit["decoder_launch_attempts"], 1)
        self.assertEqual(audit["decoder_launches"], 0)
        self.assertEqual(audit["frames_emitted"], 0)

    def test_no_follow_directory_walk_rejects_synthetic_ancestor_symlink(self):
        temporary_root = Path(__file__).resolve().parents[1] / ".bootstrap-test-tmp"
        temporary_root.mkdir(exist_ok=True)
        with tempfile.TemporaryDirectory(prefix="study2a-stream-test-", dir=temporary_root) as folder:
            base = Path(folder)
            (base / "actual").mkdir()
            (base / "alias").symlink_to("actual", target_is_directory=True)
            with self.assertRaises(OSError):
                streaming._parent_fd(str(base / "alias" / "synthetic.bin"))


class NativePipeTests(unittest.TestCase):
    """Only tiny generated bytes are piped; FFmpeg is never invoked."""

    def run_pipe(self, code, count=2, timeout=2.0):
        record = pipe_record()
        process = subprocess.Popen([sys.executable, "-B", "-c", code],
                                   stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE, bufsize=0)
        frames = []
        try:
            frames.extend(streaming._native_frames(process, 4, count, record, timeout))
            return frames, record
        finally:
            if process.poll() is None:
                process.kill()
            process.wait(timeout=5)
            process.stdout.close()
            process.stderr.close()
            self.last_record = record

    def test_reads_fragmented_frames_and_drains_large_stderr_bounded(self):
        code = "import os; os.write(2,b'e'*200000); os.write(1,b'abc'); os.write(1,b'defgh')"
        frames, record = self.run_pipe(code)
        self.assertEqual(frames, [b"abcd", b"efgh"])
        self.assertEqual(record["native_bytes_received"], 8)
        self.assertEqual(record["decoder_stderr_bytes"], 200000)
        self.assertEqual(len(record["decoder_stderr"]), streaming.STDERR_LIMIT_BYTES)
        self.assertTrue(record["decoder_stderr_truncated"])
        self.assertEqual(record["decoder_exit_code"], 0)

    def test_partial_frame_is_not_silently_accepted(self):
        with self.assertRaisesRegex(streaming.StreamingContractError, "TRUNCATED_FRAME"):
            self.run_pipe("import os; os.write(1,b'abcdef')")
        self.assertEqual(self.last_record["trailing_partial_bytes"], 2)

    def test_missing_whole_frame_fails_count(self):
        with self.assertRaisesRegex(streaming.StreamingContractError, "FRAME_COUNT_MISMATCH"):
            self.run_pipe("import os; os.write(1,b'abcd')")

    def test_extra_whole_frame_fails_before_extra_delivery(self):
        with self.assertRaisesRegex(streaming.StreamingContractError, "FRAME_COUNT_EXCEEDED"):
            self.run_pipe("import os; os.write(1,b'abcdefghijkl')")
        self.assertEqual(self.last_record["native_bytes_received"], 12)

    def test_nonzero_exit_fails_even_after_expected_payload(self):
        with self.assertRaisesRegex(streaming.StreamingContractError, "EXIT_FAILURE"):
            self.run_pipe("import os; os.write(1,b'abcdefgh'); raise SystemExit(3)")
        self.assertEqual(self.last_record["decoder_exit_code"], 3)

    def test_idle_decoder_has_a_finite_timeout(self):
        with self.assertRaisesRegex(streaming.StreamingContractError, "DECODER_TIMEOUT"):
            self.run_pipe("import time; time.sleep(5)", timeout=0.05)


if __name__ == "__main__":
    unittest.main()
