"""TI3-C receipt/runner boundaries using generated bytes and mocks only."""

import copy
import hashlib
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest import mock

from scripts import run_ti3c_cnn as runner
from snbi_fragmentation import ti3c_execution as execution
from snbi_fragmentation.ti3_dataset import build_manifest
from test_ti3_dataset import fixture


HEAD = "1" * 40


def synthetic_inputs():
    inputs = fixture()
    payloads = {}
    for image in inputs[2]:
        key = (image["source_id"], image["frame_index"])
        payloads[key] = bytes([17]) * image["frame_bytes"]
        image["image_sha256"] = hashlib.sha256(payloads[key]).hexdigest()
    manifest = build_manifest(*inputs)
    pilot = {"images": copy.deepcopy(inputs[2])}
    for image in inputs[2]:
        peer = copy.deepcopy(image)
        peer["source_id"] = execution.PAIR_SOURCE[image["source_id"]]
        peer["path"] = f"data/derived/ti2-pilot/{peer['source_id']}-{peer['frame_index']:04d}.raw"
        key = (peer["source_id"], peer["frame_index"])
        payloads[key] = bytes([29]) * peer["frame_bytes"]
        peer["image_sha256"] = hashlib.sha256(payloads[key]).hexdigest()
        pilot["images"].append(peer)
    inventory = execution.build_inventory(manifest, pilot)
    serialized = execution.canonical_bytes(manifest)
    authority = {"state": "ARMED_ONCE", "head_sha": HEAD, "scientific_invocation_limit": 1,
                 "manifest_sha256": hashlib.sha256(serialized).hexdigest(),
                 "inventory_sha256": hashlib.sha256(execution.canonical_bytes(inventory)).hexdigest(),
                 "method_freeze_sha256": "e" * 64}
    return manifest, pilot, inventory, serialized, authority, payloads


class MetadataTrap(dict):
    def get(self, key, default=None):
        if key == "path":
            raise AssertionError("forbidden path was examined")
        return super().get(key, default)


class PairedAdmissionTests(unittest.TestCase):
    def test_all_final_and_forbidden_sources_deny_before_path_stat_or_open(self):
        cases = [dict(split="FINAL_TEST", source_id=s, frame_index=i) for s, i in execution.SEALED_FRAMES]
        cases += [dict(split="TRAIN", source_id="ESM3", frame_index=73),
                  dict(split="TRAIN", source_id="ESM6", frame_index=98),
                  dict(split="TRAIN", source_id="ESM2", frame_index=293),
                  dict(split="TRAIN", source_id="ESM5", frame_index=197),
                  dict(split="TRAIN", source_id="ESM1", frame_index=True)]
        with mock.patch.object(execution.os, "open") as opened, mock.patch.object(execution.os, "stat") as stated:
            for record in cases:
                with self.subTest(record=record), self.assertRaises(execution.ExecutionContractError):
                    execution.validate_admission(MetadataTrap(record))
            opened.assert_not_called()
            stated.assert_not_called()

    def test_numeric_types_are_exact_recursively(self):
        self.assertTrue(execution.exact({"a": [1, 1.0, True]}, {"a": [1, 1.0, True]}))
        for value in (True, 1.0):
            self.assertFalse(execution.exact({"a": [1]}, {"a": [value]}))

    def test_textual_pairing_binds_layout_hashes_and_sealed_inventory(self):
        manifest, pilot, inventory, _, _, _ = synthetic_inputs()
        self.assertEqual(len(inventory), 14)
        self.assertEqual(sum(r["split"] != "FINAL_TEST" for r in inventory), 10)
        self.assertEqual(sum(r["frame_bytes"] for r in inventory if r["split"] != "FINAL_TEST"), 19469052)
        self.assertEqual([r for r in inventory if r["source_id"] in execution.PAIR_SOURCE], manifest["source_inventory"])
        bad = copy.deepcopy(pilot)
        bad["images"][0]["image_sha256"] = "f" * 64
        with self.assertRaisesRegex(execution.ExecutionContractError, "STRUCTURAL_PILOT_DIVERGENCE"):
            execution.build_inventory(manifest, bad)

    def test_missing_duplicate_and_mispaired_pilot_records_fail(self):
        manifest, pilot, _, _, _, _ = synthetic_inputs()
        for corruption in ("missing", "duplicate", "dimensions", "acquisition"):
            bad = copy.deepcopy(pilot)
            if corruption == "missing":
                bad["images"].pop()
            elif corruption == "duplicate":
                bad["images"].append(copy.deepcopy(bad["images"][0]))
            elif corruption == "dimensions":
                bad["images"][-1]["height"] = 1018
            else:
                bad["images"][-1]["experiment_id"] = "other-acquisition"
            with self.subTest(corruption=corruption), self.assertRaises(execution.ExecutionContractError):
                execution.build_inventory(manifest, bad)


class ReceiptAndNativeSyntheticTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.manifest, cls.pilot, cls.inventory, cls.serialized, cls.authority, cls.payloads = synthetic_inputs()

    def setUp(self):
        parent = Path(".bootstrap-test-tmp/ti3-preflight-recovery")
        if parent.is_dir():
            temporary = tempfile.TemporaryDirectory(prefix="ti3c-io-", dir=parent)
        elif os.environ.get("CI") == "true":
            temporary = tempfile.TemporaryDirectory(prefix="ti3c-io-ci-")
        else:
            self.fail("authorized local synthetic temporary root is unavailable")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).absolute()
        (self.root / execution.RECEIPT_PATH).parent.mkdir(parents=True)
        (self.root / "data/derived/ti2-pilot").mkdir(parents=True)
        self.record = copy.deepcopy(next(r for r in self.inventory if (r["source_id"], r["frame_index"]) == ("ESM2", 73)))

    def arm(self, authority=None, head=HEAD):
        reader = execution.arm_execution(self.root, self.serialized, self.inventory,
                                         self.authority if authority is None else authority, head)
        self.addCleanup(reader.close)
        return reader

    def write_source(self, record=None, payload=None):
        record = self.record if record is None else record
        if payload is None:
            payload = self.payloads[(record["source_id"], record["frame_index"])]
        (self.root / record["path"]).write_bytes(payload)

    def test_receipt_is_durable_before_first_native_open(self):
        self.write_source()
        actual_open, actual_fsync = os.open, os.fsync
        fsync_calls = []
        def synced(fd):
            fsync_calls.append(fd)
            return actual_fsync(fd)
        def opened(path, flags, *args, **kwargs):
            if path == "ESM2-0073.raw":
                self.assertGreaterEqual(len(fsync_calls), 2)
                self.assertTrue(flags & os.O_NOFOLLOW)
                self.assertFalse(flags & os.O_WRONLY)
            return actual_open(path, flags, *args, **kwargs)
        with mock.patch.object(execution.os, "open", side_effect=opened), mock.patch.object(execution.os, "fsync", side_effect=synced):
            reader = self.arm()
            self.assertEqual(reader.read_native(self.record), self.payloads[("ESM2", 73)])
        receipt = json.loads((self.root / execution.RECEIPT_PATH).read_text())
        self.assertEqual(receipt["experimental_opens_at_receipt"], 0)
        self.assertEqual(receipt["scientific_invocation"], 1)

    def test_all_ten_buffers_once_and_four_final_records_never_open(self):
        reader = self.arm()
        for record in self.inventory:
            if record["split"] != "FINAL_TEST":
                self.write_source(record)
                reader.read_native(record)
        report = reader.report()
        self.assertEqual(report["experimental_opens"], 10)
        self.assertEqual(report["experimental_bytes"], 19469052)
        self.assertEqual(report["solutal_opens"], 5)
        self.assertEqual(report["solutal_bytes"], 9734526)
        self.assertEqual(report["structural_opens"], 5)
        self.assertEqual(report["final_test_opens"], 0)
        self.assertEqual(report["final_test_bytes"], 0)
        self.assertTrue(all(r["status"] == "NOT_OPENED" for r in report["entries"] if r["split"] == "FINAL_TEST"))

    def test_final_denial_before_any_filesystem_access_on_armed_reader(self):
        reader = self.arm()
        with mock.patch.object(execution.os, "open") as opened, mock.patch.object(execution.os, "stat") as stated:
            for record in self.inventory:
                if record["split"] == "FINAL_TEST":
                    with self.assertRaises(execution.ExecutionContractError):
                        reader.read_native(record)
            opened.assert_not_called()
            stated.assert_not_called()

    def test_second_read_is_denied_without_another_open(self):
        self.write_source()
        reader = self.arm()
        reader.read_native(self.record)
        with mock.patch.object(execution.os, "open") as opened:
            with self.assertRaisesRegex(execution.ExecutionContractError, "SOURCE_ALREADY_ATTEMPTED"):
                reader.read_native(self.record)
            opened.assert_not_called()

    def test_receipt_and_terminal_permanently_deny_rearming(self):
        self.arm()
        with self.assertRaisesRegex(execution.ExecutionContractError, "RECEIPT_ALREADY_EXISTS"):
            self.arm()
        (self.root / execution.TERMINAL_PATH).write_text("{}")
        with self.assertRaisesRegex(execution.ExecutionContractError, "TERMINAL_ALREADY_EXISTS"):
            self.arm()

    def test_invalid_custody_fails_before_any_open(self):
        for field, value in (("head_sha", "2" * 40), ("manifest_sha256", "b" * 64),
                             ("inventory_sha256", "c" * 64), ("scientific_invocation_limit", True),
                             ("scientific_invocation_limit", 1.0), ("state", "CONSUMED")):
            authority = dict(self.authority, **{field: value})
            with self.subTest(field=field, value=value), mock.patch.object(execution.os, "open") as opened:
                with self.assertRaises(execution.ExecutionContractError):
                    self.arm(authority)
                opened.assert_not_called()

    def test_hash_failure_poisons_reader_and_keeps_factual_counts(self):
        self.write_source(payload=bytes([31]) * self.record["frame_bytes"])
        reader = self.arm()
        with self.assertRaisesRegex(execution.ExecutionContractError, "NATIVE_HASH_MISMATCH"):
            reader.read_native(self.record)
        self.assertEqual(reader.report()["experimental_bytes"], self.record["frame_bytes"])
        other = next(r for r in self.inventory if (r["source_id"], r["frame_index"]) == ("ESM1", 73))
        with mock.patch.object(execution.os, "open") as opened:
            with self.assertRaisesRegex(execution.ExecutionContractError, "READER_CLOSED_OR_FAILED"):
                reader.read_native(other)
            opened.assert_not_called()

    def test_size_failure_never_reads_extra_bytes(self):
        self.write_source(payload=self.payloads[("ESM2", 73)] + b"extra")
        reader = self.arm()
        with mock.patch.object(execution.os, "read") as read:
            with self.assertRaisesRegex(execution.ExecutionContractError, "NATIVE_BYTE_COUNT_MISMATCH"):
                reader.read_native(self.record)
            read.assert_not_called()
        self.assertEqual(reader.report()["experimental_bytes"], 0)
        self.assertEqual(reader.report()["experimental_opens"], 1)

    def test_partial_read_error_preserves_partial_bytes_and_denies_retry(self):
        self.write_source()
        reader = self.arm()
        actual_read, calls = os.read, []
        def interrupted(fd, size):
            calls.append(size)
            if len(calls) > 1:
                raise OSError("synthetic interruption")
            return actual_read(fd, 19)
        with mock.patch.object(execution.os, "read", side_effect=interrupted):
            with self.assertRaisesRegex(execution.ExecutionContractError, "NATIVE_IO_FAILED"):
                reader.read_native(self.record)
        self.assertEqual(reader.report()["experimental_bytes"], 19)
        self.assertTrue(reader.report()["failed"])

    def test_leaf_symlink_denied_without_reading_target(self):
        target = self.root / "synthetic-target"
        target.write_bytes(b"synthetic")
        (self.root / self.record["path"]).symlink_to(target)
        reader = self.arm()
        with self.assertRaises(execution.ExecutionContractError):
            reader.read_native(self.record)
        self.assertEqual(reader.report()["experimental_opens"], 0)

    def test_parent_symlink_denied_before_source_attempt(self):
        parent = self.root / "data/derived/ti2-pilot"
        parent.rmdir()
        target = self.root / "synthetic-parent"
        target.mkdir()
        parent.symlink_to(target, target_is_directory=True)
        reader = self.arm()
        with self.assertRaises(execution.ExecutionContractError):
            reader.read_native(self.record)
        self.assertEqual(reader.report()["source_open_attempts"], 0)

    def test_terminal_appearing_after_receipt_blocks_source_read(self):
        reader = self.arm()
        (self.root / execution.TERMINAL_PATH).write_text("{}")
        with self.assertRaisesRegex(execution.ExecutionContractError, "TERMINAL_ALREADY_EXISTS"):
            reader.read_native(self.record)
        self.assertEqual(reader.report()["experimental_opens"], 0)

    def test_report_copy_and_closed_reader_do_not_reopen(self):
        reader = self.arm()
        report = reader.report()
        report["entries"][0]["opens"] = 99
        self.assertEqual(reader.report()["experimental_opens"], 0)
        reader.close()
        with mock.patch.object(execution.os, "open") as opened:
            with self.assertRaises(execution.ExecutionContractError):
                reader.read_native(self.record)
            opened.assert_not_called()


class RunnerMetadataTests(unittest.TestCase):
    def proof(self):
        return {"head_sha": HEAD, "repository": runner.REPOSITORY, "runs": [
            {"head_sha": HEAD, "status": "completed", "conclusion": "success", "jobs": [
                {"name": name, "status": "completed", "conclusion": "success",
                 "steps": [{"name": "synthetic", "status": "completed", "conclusion": "success"}]}
                for name in runner.REQUIRED_JOBS]}]}

    def test_five_complete_green_jobs_at_exact_head_are_required(self):
        runner.validate_ci(self.proof(), HEAD)
        for corrupt in ("head", "job", "step", "missing", "no-steps"):
            proof = self.proof()
            if corrupt == "head":
                proof["runs"][0]["head_sha"] = "2" * 40
            elif corrupt == "job":
                proof["runs"][0]["jobs"][0]["conclusion"] = "cancelled"
            elif corrupt == "step":
                proof["runs"][0]["jobs"][0]["steps"][0]["conclusion"] = "skipped"
            elif corrupt == "missing":
                proof["runs"][0]["jobs"].pop()
            else:
                proof["runs"][0]["jobs"][0]["steps"] = []
            with self.subTest(corrupt=corrupt), self.assertRaises(execution.ExecutionContractError):
                runner.validate_ci(proof, HEAD)

    def test_consumed_authority_denies_before_git_or_text(self):
        with mock.patch.object(runner.os.path, "lexists", return_value=True), \
             mock.patch.object(runner, "_git") as git, mock.patch.object(runner, "_read_text") as read:
            with self.assertRaisesRegex(execution.ExecutionContractError, "TI3C_AUTHORITY_ALREADY_CONSUMED"):
                runner._preflight()
            git.assert_not_called()
            read.assert_not_called()

    def test_preflight_denial_records_zero_counts_without_arming(self):
        written = {}
        with mock.patch.object(runner, "_preflight", side_effect=execution.ExecutionContractError("SYNTHETIC_PREFLIGHT_DENIAL")), \
             mock.patch.object(runner.os.path, "lexists", return_value=False), \
             mock.patch.object(runner, "_write_once", side_effect=lambda n, v: written.update({n: v})), \
             mock.patch.object(runner, "arm_execution") as arm, mock.patch("builtins.print"):
            self.assertEqual(runner.main(), 3)
            arm.assert_not_called()
        self.assertEqual(written["results.json"]["experimental_opens"], 0)
        self.assertEqual(written["results.json"]["SCIENTIFIC_TI3C_RUNS"], 0)

    def test_final_materialization_is_denied_before_metadata_or_array_access(self):
        reader, np = mock.Mock(), mock.Mock()
        with self.assertRaisesRegex(execution.ExecutionContractError, "FINAL_OR_UNKNOWN_SPLIT_DENIED"):
            runner.materialize_split("FINAL_TEST", None, None, reader, None, None, np, [])
        reader.read_native.assert_not_called()
        np.stack.assert_not_called()

    def test_reference_requires_closed_b_and_unchanged_both_patch_hashes(self):
        manifest = build_manifest(*fixture())
        order = {split: [] for split in ("TRAIN", "DEVELOPMENT")}
        for source in manifest["source_inventory"]:
            if source["split"] != "FINAL_TEST":
                order[source["split"]].extend(sorted(s["sample_id"] for s in manifest["samples"]
                    if (s["source_id"], s["frame_index"]) == (source["source_id"], source["frame_index"])))
        # Use exactly fifty generated active records and six sealed records.
        active_samples = [s for s in manifest["samples"] if s["split"] != "FINAL_TEST"]
        sealed_samples = [s for s in manifest["samples"] if s["split"] == "FINAL_TEST"]
        while len(active_samples) < 50:
            sample = dict(active_samples[0], sample_id="synthetic-active-" + str(len(active_samples)))
            active_samples.append(sample)
        while len(sealed_samples) < 6:
            sealed_samples.append(dict(sealed_samples[0], sample_id="synthetic-final-" + str(len(sealed_samples))))
        manifest["samples"] = active_samples[:50] + sealed_samples[:6]
        order = {split: [] for split in ("TRAIN", "DEVELOPMENT")}
        for source in manifest["source_inventory"]:
            if source["split"] != "FINAL_TEST":
                order[source["split"]].extend(sorted(s["sample_id"] for s in manifest["samples"]
                    if (s["source_id"], s["frame_index"]) == (source["source_id"], source["frame_index"])))
        materialization = {"samples": [], "final_samples": []}
        for sample in manifest["samples"]:
            if sample["split"] == "FINAL_TEST":
                materialization["final_samples"].append({"sample_id": sample["sample_id"], "split": "FINAL_TEST",
                    "structural_input_opened": False, "solutal_input_opened": False,
                    "structural_patch_sha256": None, "solutal_patch_sha256": None, "feature_sha256": None})
            else:
                materialization["samples"].append({"sample_id": sample["sample_id"], "split": sample["split"],
                    "structural_source_id": sample["source_id"], "solutal_source_id": runner.PAIR_SOURCE[sample["source_id"]],
                    "frame_index": sample["frame_index"], "center_x": sample["center_x"], "center_y": sample["center_y"],
                    "patch_side_px": 65, "structural_patch_sha256": "a" * 64, "solutal_patch_sha256": "b" * 64})
        result = {"TI3_B": "PASS", "SCIENTIFIC_TI3B_RUNS": 1, "ML_FINAL_TEST_EXECUTED": False,
                  "sample_order": order, "ablation": {"dev_modality_preference": "STRUCTURAL_PLUS_RELATIVE_SOLUTE",
                    "evaluations": {"DEVELOPMENT": {"balanced_accuracy": 0.75, "confusion_matrix": [[4, 4], [0, 8]]}}}}
        terminal = {"STATE": "CLOSED_CONSUMED", "TI3_B_EXECUTION_AUTHORIZED": False,
                    **{k: 0 for k in ("FINAL_STRUCTURAL_OPENS", "FINAL_STRUCTURAL_BYTES", "FINAL_SOLUTAL_OPENS", "FINAL_SOLUTAL_BYTES")}}
        previous, actual_order = runner._validate_reference(manifest, result, terminal, materialization)
        self.assertEqual(len(previous), 50)
        self.assertEqual(actual_order, order)
        for field, value in (("center_x", -10), ("solutal_patch_sha256", None), ("structural_patch_sha256", None)):
            bad = copy.deepcopy(materialization)
            bad["samples"][0][field] = value
            with self.subTest(field=field), self.assertRaises(execution.ExecutionContractError):
                runner._validate_reference(manifest, result, terminal, bad)
        with self.assertRaises(execution.ExecutionContractError):
            runner._validate_reference(manifest, result, dict(terminal, STATE="OPEN"), materialization)


class RunnerSyntheticControlTests(unittest.TestCase):
    def setup_mocks(self, stack):
        manifest, _, inventory, serialized, active, _ = synthetic_inputs()
        order = {"TRAIN": ["train"], "DEVELOPMENT": ["dev"]}
        events, written = [], {}
        reader, np = mock.Mock(), mock.Mock()
        current = {"split": None}
        def materialize(split, manifest, inventory, reader, previous, expected_order, np, patches):
            events.append("materialize-" + split)
            current["split"] = split
            patches.append({"sample_id": split, "split": split})
            return split + "-array", [0], [{"sample_id": split, "split": split}]
        def report():
            train_only = current["split"] == "TRAIN"
            return {"experimental_opens": 6 if train_only else 10,
                    "experimental_bytes": 11686032 if train_only else 19469052,
                    "final_test_opens": 0, "final_test_bytes": 0,
                    "entries": [{"split": "FINAL_TEST", "opens": 0},
                                {"split": "DEVELOPMENT", "opens": 0 if train_only else 4}]}
        reader.report.side_effect = report
        def train(*args):
            events.append("train")
            return "model", {"epoch_losses": [1.0] * 10, "parameter_count": 170}
        def evaluate(model, inputs, labels, samples, split):
            events.append("evaluate-" + split)
            return {"balanced_accuracy": 0.5}
        stack.enter_context(mock.patch.object(runner, "_preflight", return_value=(HEAD, manifest, serialized, inventory,
                           active, {}, order, np, {"torch": "2.4.1+cpu"}, {})))
        stack.enter_context(mock.patch.object(runner, "arm_execution", return_value=reader))
        materializer = stack.enter_context(mock.patch.object(runner, "materialize_split", side_effect=materialize))
        trainer = stack.enter_context(mock.patch.object(runner, "train_fixed", side_effect=train))
        evaluator = stack.enter_context(mock.patch.object(runner, "evaluate_fixed", side_effect=evaluate))
        stack.enter_context(mock.patch.object(runner, "_write_once", side_effect=lambda n, v: written.update({n: v})))
        stack.enter_context(mock.patch("builtins.print"))
        return reader, materializer, trainer, evaluator, events, written

    def test_exact_sequence_one_training_then_train_eval_then_dev_open_eval(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            reader, materializer, trainer, evaluator, events, written = self.setup_mocks(stack)
            self.assertEqual(runner.main(), 0)
            self.assertEqual(events, ["materialize-TRAIN", "train", "evaluate-TRAIN",
                                      "materialize-DEVELOPMENT", "evaluate-DEVELOPMENT"])
            trainer.assert_called_once()
            self.assertEqual(evaluator.call_count, 2)
            self.assertEqual(materializer.call_count, 2)
            reader.close.assert_called_once()
        result = written["results.json"]
        self.assertEqual(result["SCIENTIFIC_TI3C_RUNS"], 1)
        self.assertEqual(result["selection"]["final_model_family_preference"], "MULTIMODAL_LBP_RF")
        sealed = written["materialization-manifest.json"]["final_samples"][0]
        self.assertFalse(sealed["solutal_input_opened"])
        self.assertIsNone(sealed["input_uint8_sha256"])

    def test_train_support_failure_prevents_any_training_or_dev(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            _, materializer, trainer, evaluator, _, written = self.setup_mocks(stack)
            materializer.side_effect = execution.ExecutionContractError("BLOCKED_SUPPORT")
            self.assertEqual(runner.main(), 2)
            trainer.assert_not_called()
            evaluator.assert_not_called()
            materializer.assert_called_once()
        self.assertEqual(written["results.json"]["training_calls_started"], 0)

    def test_training_failure_never_opens_dev_or_retries(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            _, materializer, trainer, evaluator, _, written = self.setup_mocks(stack)
            trainer.side_effect = RuntimeError("synthetic training failure")
            self.assertEqual(runner.main(), 2)
            trainer.assert_called_once()
            materializer.assert_called_once()
            evaluator.assert_not_called()
        self.assertEqual(written["results.json"]["training_calls_started"], 1)
        self.assertEqual(written["results.json"]["SCIENTIFIC_TI3C_RUNS"], 1)
        self.assertEqual(written["results.json"]["SCIENTIFIC_TI3C_COMPLETED_RUNS"], 0)

    def test_dev_support_failure_after_training_keeps_train_evidence_without_retry(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            _, materializer, trainer, evaluator, _, written = self.setup_mocks(stack)
            original = materializer.side_effect
            def fail_dev(split, *args):
                if split == "DEVELOPMENT":
                    raise execution.ExecutionContractError("BLOCKED_DEV_SUPPORT")
                return original(split, *args)
            materializer.side_effect = fail_dev
            self.assertEqual(runner.main(), 2)
            trainer.assert_called_once()
            evaluator.assert_called_once()
        self.assertIsNotNone(written["results.json"]["completed_train_evaluation"])
        self.assertEqual(written["results.json"]["development_evaluations_started"], 0)

    def test_dev_evaluation_failure_is_one_attempt_and_no_model_selection(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            _, _, trainer, evaluator, _, written = self.setup_mocks(stack)
            original = evaluator.side_effect
            def fail_dev(model, inputs, labels, samples, split):
                if split == "DEVELOPMENT":
                    raise RuntimeError("synthetic evaluation failure")
                return original(model, inputs, labels, samples, split)
            evaluator.side_effect = fail_dev
            self.assertEqual(runner.main(), 2)
            trainer.assert_called_once()
            self.assertEqual(evaluator.call_count, 2)
        self.assertEqual(written["results.json"]["development_evaluations_started"], 1)
        self.assertNotIn("selection", written["results.json"])


if __name__ == "__main__":
    unittest.main()
