"""TI3-D receipt/runner boundaries using generated bytes and mocks only."""

import copy
import hashlib
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest import mock

from scripts import run_ti3d_final as runner
from snbi_fragmentation import ti3d_execution as execution
from snbi_fragmentation.ti3_baseline import RF_PARAMETERS


HEAD = "1" * 40


def synthetic_inputs():
    # Only the already-versioned textual geometry is read. Every native byte in
    # this fixture is generated here, under an isolated temporary repository.
    manifest = json.loads(Path("artifacts/evidence/TI3_A_RESUME/dataset_manifest.json").read_text())
    payloads, pilot = {}, {"images": []}
    for image in manifest["source_inventory"]:
        for source in (image["source_id"], execution.PAIR_SOURCE[image["source_id"]]):
            key = (source, image["frame_index"])
            payloads[key] = bytes([17 if source in execution.PAIR_SOURCE else 29]) * image["frame_bytes"]
            digest = hashlib.sha256(payloads[key]).hexdigest()
            if source == image["source_id"]:
                image["image_sha256"] = digest
                for sample in manifest["samples"]:
                    if (sample["source_id"], sample["frame_index"]) == key:
                        sample["image_sha256"] = digest
                        sample["provenance"]["known_native_sha256"] = digest
            peer = copy.deepcopy(image)
            peer.update(source_id=source, path=f"data/derived/ti2-pilot/{source}-{key[1]:04d}.raw",
                        image_sha256=digest, experiment_id=image["acquisition_id"], planes=[image["y_plane"]])
            pilot["images"].append(peer)
    inventory = execution.build_inventory(manifest, pilot)
    serialized = execution.canonical_bytes(manifest)
    authority = {"state": "ARMED_ONCE", "head_sha": HEAD, "scientific_invocation_limit": 1,
                 "manifest_sha256": hashlib.sha256(serialized).hexdigest(),
                 "inventory_sha256": hashlib.sha256(execution.canonical_bytes(inventory)).hexdigest(),
                 "method_freeze_sha256": "e" * 64}
    return manifest, pilot, inventory, serialized, authority, payloads


class MetadataTrap(dict):
    def get(self, key, default=None):
        if key == "path":
            raise AssertionError("forbidden path was examined")
        return super().get(key, default)


class PairedAdmissionTests(unittest.TestCase):
    def test_forbidden_sources_deny_before_path_stat_or_open(self):
        cases = [dict(split="TRAIN", source_id="ESM3", frame_index=73),
                  dict(split="TRAIN", source_id="ESM6", frame_index=98),
                  dict(split="TRAIN", source_id="ESM2", frame_index=293),
                  dict(split="TRAIN", source_id="ESM5", frame_index=197),
                  dict(split="TRAIN", source_id="ESM1", frame_index=True)]
        with mock.patch.object(execution.os, "open") as opened, mock.patch.object(execution.os, "stat") as stated:
            for record in cases:
                with self.subTest(record=record), self.assertRaises(execution.ExecutionContractError):
                    execution.validate_admission(MetadataTrap(record))
            opened.assert_not_called()
            stated.assert_not_called()

    def test_numeric_types_are_exact_recursively(self):
        self.assertTrue(execution.exact({"a": [1, 1.0, True]}, {"a": [1, 1.0, True]}))
        for value in (True, 1.0):
            self.assertFalse(execution.exact({"a": [1]}, {"a": [value]}))

    def test_textual_pairing_binds_layout_hashes_and_sealed_inventory(self):
        manifest, pilot, inventory, _, _, _ = synthetic_inputs()
        self.assertEqual(len(inventory), 14)
        self.assertEqual(sum(r["split"] != "FINAL_TEST" for r in inventory), 10)
        self.assertEqual(sum(r["frame_bytes"] for r in inventory if r["split"] != "FINAL_TEST"), 19469052)
        self.assertEqual([r for r in inventory if r["source_id"] in execution.PAIR_SOURCE], manifest["source_inventory"])
        bad = copy.deepcopy(pilot)
        bad["images"][0]["image_sha256"] = "f" * 64
        with self.assertRaisesRegex(execution.ExecutionContractError, "STRUCTURAL_PILOT_DIVERGENCE"):
            execution.build_inventory(manifest, bad)

    def test_missing_duplicate_and_mispaired_pilot_records_fail(self):
        manifest, pilot, _, _, _, _ = synthetic_inputs()
        for corruption in ("missing", "duplicate", "dimensions", "acquisition"):
            bad = copy.deepcopy(pilot)
            if corruption == "missing":
                bad["images"].pop()
            elif corruption == "duplicate":
                bad["images"].append(copy.deepcopy(bad["images"][0]))
            elif corruption == "dimensions":
                bad["images"][-1]["height"] = 1018
            else:
                bad["images"][-1]["experiment_id"] = "other-acquisition"
            with self.subTest(corruption=corruption), self.assertRaises(execution.ExecutionContractError):
                execution.build_inventory(manifest, bad)


class ReceiptAndNativeSyntheticTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.manifest, cls.pilot, cls.inventory, cls.serialized, cls.authority, cls.payloads = synthetic_inputs()

    def setUp(self):
        parent = Path(".bootstrap-test-tmp/ti3-preflight-recovery")
        if parent.is_dir():
            temporary = tempfile.TemporaryDirectory(prefix="ti3d-io-", dir=parent)
        elif os.environ.get("CI") == "true":
            temporary = tempfile.TemporaryDirectory(prefix="ti3d-io-ci-")
        else:
            self.fail("authorized local synthetic temporary root is unavailable")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).absolute()
        (self.root / execution.RECEIPT_PATH).parent.mkdir(parents=True)
        (self.root / "data/derived/ti2-pilot").mkdir(parents=True)
        self.record = copy.deepcopy(next(r for r in self.inventory if (r["source_id"], r["frame_index"]) == ("ESM2", 73)))

    def arm(self, authority=None, head=HEAD):
        reader = execution.arm_execution(self.root, self.serialized, self.inventory,
                                         self.authority if authority is None else authority, head)
        self.addCleanup(reader.close)
        return reader

    def write_source(self, record=None, payload=None):
        record = self.record if record is None else record
        if payload is None:
            payload = self.payloads[(record["source_id"], record["frame_index"])]
        (self.root / record["path"]).write_bytes(payload)

    def test_receipt_is_durable_before_first_native_open(self):
        self.write_source()
        actual_open, actual_fsync = os.open, os.fsync
        fsync_calls = []
        def synced(fd):
            fsync_calls.append(fd)
            return actual_fsync(fd)
        def opened(path, flags, *args, **kwargs):
            if path == "ESM2-0073.raw":
                self.assertGreaterEqual(len(fsync_calls), 2)
                self.assertTrue(flags & os.O_NOFOLLOW)
                self.assertFalse(flags & os.O_WRONLY)
            return actual_open(path, flags, *args, **kwargs)
        with mock.patch.object(execution.os, "open", side_effect=opened), mock.patch.object(execution.os, "fsync", side_effect=synced):
            reader = self.arm()
            self.assertEqual(reader.read_native(self.record), self.payloads[("ESM2", 73)])
        receipt = json.loads((self.root / execution.RECEIPT_PATH).read_text())
        self.assertEqual(receipt["experimental_opens_at_receipt"], 0)
        self.assertEqual(receipt["scientific_invocation"], 1)

    def test_all_ten_buffers_once_and_four_final_records_never_open(self):
        reader = self.arm()
        for record in self.inventory:
            if record["split"] != "FINAL_TEST":
                self.write_source(record)
                reader.read_native(record)
        report = reader.report()
        self.assertEqual(report["experimental_opens"], 10)
        self.assertEqual(report["experimental_bytes"], 19469052)
        self.assertEqual(report["solutal_opens"], 5)
        self.assertEqual(report["solutal_bytes"], 9734526)
        self.assertEqual(report["structural_opens"], 5)
        self.assertEqual(report["final_test_opens"], 0)
        self.assertEqual(report["final_test_bytes"], 0)
        self.assertTrue(all(r["status"] == "NOT_OPENED" for r in report["entries"] if r["split"] == "FINAL_TEST"))

    def test_final_denial_before_any_filesystem_access_on_armed_reader(self):
        reader = self.arm()
        with mock.patch.object(execution.os, "open") as opened, mock.patch.object(execution.os, "stat") as stated:
            for record in self.inventory:
                if record["split"] == "FINAL_TEST":
                    with self.assertRaises(execution.ExecutionContractError):
                        reader.read_native(record)
            opened.assert_not_called()
            stated.assert_not_called()

    def test_second_read_is_denied_without_another_open(self):
        self.write_source()
        reader = self.arm()
        reader.read_native(self.record)
        with mock.patch.object(execution.os, "open") as opened:
            with self.assertRaisesRegex(execution.ExecutionContractError, "SOURCE_ALREADY_ATTEMPTED"):
                reader.read_native(self.record)
            opened.assert_not_called()

    def test_receipt_and_terminal_permanently_deny_rearming(self):
        self.arm()
        with self.assertRaisesRegex(execution.ExecutionContractError, "RECEIPT_ALREADY_EXISTS"):
            self.arm()
        (self.root / execution.TERMINAL_PATH).write_text("{}")
        with self.assertRaisesRegex(execution.ExecutionContractError, "TERMINAL_ALREADY_EXISTS"):
            self.arm()

    def test_invalid_custody_fails_before_any_open(self):
        for field, value in (("head_sha", "2" * 40), ("manifest_sha256", "b" * 64),
                             ("inventory_sha256", "c" * 64), ("scientific_invocation_limit", True),
                             ("scientific_invocation_limit", 1.0), ("state", "CONSUMED")):
            authority = dict(self.authority, **{field: value})
            with self.subTest(field=field, value=value), mock.patch.object(execution.os, "open") as opened:
                with self.assertRaises(execution.ExecutionContractError):
                    self.arm(authority)
                opened.assert_not_called()

    def test_hash_failure_poisons_reader_and_keeps_factual_counts(self):
        self.write_source(payload=bytes([31]) * self.record["frame_bytes"])
        reader = self.arm()
        with self.assertRaisesRegex(execution.ExecutionContractError, "NATIVE_HASH_MISMATCH"):
            reader.read_native(self.record)
        self.assertEqual(reader.report()["experimental_bytes"], self.record["frame_bytes"])
        other = next(r for r in self.inventory if (r["source_id"], r["frame_index"]) == ("ESM1", 73))
        with mock.patch.object(execution.os, "open") as opened:
            with self.assertRaisesRegex(execution.ExecutionContractError, "READER_CLOSED_OR_FAILED"):
                reader.read_native(other)
            opened.assert_not_called()

    def test_size_failure_never_reads_extra_bytes(self):
        self.write_source(payload=self.payloads[("ESM2", 73)] + b"extra")
        reader = self.arm()
        with mock.patch.object(execution.os, "read") as read:
            with self.assertRaisesRegex(execution.ExecutionContractError, "NATIVE_BYTE_COUNT_MISMATCH"):
                reader.read_native(self.record)
            read.assert_not_called()
        self.assertEqual(reader.report()["experimental_bytes"], 0)
        self.assertEqual(reader.report()["experimental_opens"], 1)

    def test_partial_read_error_preserves_partial_bytes_and_denies_retry(self):
        self.write_source()
        reader = self.arm()
        actual_read, calls = os.read, []
        def interrupted(fd, size):
            calls.append(size)
            if len(calls) > 1:
                raise OSError("synthetic interruption")
            return actual_read(fd, 19)
        with mock.patch.object(execution.os, "read", side_effect=interrupted):
            with self.assertRaisesRegex(execution.ExecutionContractError, "NATIVE_IO_FAILED"):
                reader.read_native(self.record)
        self.assertEqual(reader.report()["experimental_bytes"], 19)
        self.assertTrue(reader.report()["failed"])

    def test_leaf_symlink_denied_without_reading_target(self):
        target = self.root / "synthetic-target"
        target.write_bytes(b"synthetic")
        (self.root / self.record["path"]).symlink_to(target)
        reader = self.arm()
        with self.assertRaises(execution.ExecutionContractError):
            reader.read_native(self.record)
        self.assertEqual(reader.report()["experimental_opens"], 0)

    def test_parent_symlink_denied_before_source_attempt(self):
        parent = self.root / "data/derived/ti2-pilot"
        parent.rmdir()
        target = self.root / "synthetic-parent"
        target.mkdir()
        parent.symlink_to(target, target_is_directory=True)
        reader = self.arm()
        with self.assertRaises(execution.ExecutionContractError):
            reader.read_native(self.record)
        self.assertEqual(reader.report()["source_open_attempts"], 0)

    def test_terminal_appearing_after_receipt_blocks_source_read(self):
        reader = self.arm()
        (self.root / execution.TERMINAL_PATH).write_text("{}")
        with self.assertRaisesRegex(execution.ExecutionContractError, "TERMINAL_ALREADY_EXISTS"):
            reader.read_native(self.record)
        self.assertEqual(reader.report()["experimental_opens"], 0)

    def test_report_copy_and_closed_reader_do_not_reopen(self):
        reader = self.arm()
        report = reader.report()
        report["entries"][0]["opens"] = 99
        self.assertEqual(reader.report()["experimental_opens"], 0)
        reader.close()
        with mock.patch.object(execution.os, "open") as opened:
            with self.assertRaises(execution.ExecutionContractError):
                reader.read_native(self.record)
            opened.assert_not_called()



    def complete_training(self, reader):
        for record in self.inventory:
            if record["split"] != "FINAL_TEST":
                self.write_source(record)
                reader.read_native(record)
        ids = []
        for split in ("TRAIN", "DEVELOPMENT"):
            for source in self.manifest["source_inventory"]:
                if source["split"] == split:
                    ids.extend(sorted(s["sample_id"] for s in self.manifest["samples"]
                        if (s["source_id"], s["frame_index"]) == (source["source_id"], source["frame_index"])))
        record = {"schema": "TI3D-FINAL-FIT-1", "final_fit_calls": 1,
                  "training_sample_ids": ids, "parameters": RF_PARAMETERS,
                  "feature_dimension": 20, "model_family": "MULTIMODAL_LBP_RF",
                  "logical_model_sha256": "a" * 64}
        payload = runner.evidence_bytes(record)
        (self.root / execution.FIT_PATH).write_bytes(payload)
        return hashlib.sha256(payload).hexdigest(), record

    def test_final_authorization_requires_all_training_reads(self):
        reader = self.arm()
        with mock.patch.object(execution.os, "open") as opened:
            with self.assertRaisesRegex(execution.ExecutionContractError, "FINAL_BEFORE_TRAINING_READS_DENIED"):
                reader.authorize_final("a" * 64)
            opened.assert_not_called()

    def test_exact_fit_freeze_enables_four_final_reads_once(self):
        reader = self.arm()
        digest, _ = self.complete_training(reader)
        reader.authorize_final(digest)
        for record in self.inventory:
            if record["split"] == "FINAL_TEST":
                self.write_source(record)
                reader.read_native(record)
        report = reader.report()
        self.assertEqual(report["experimental_opens"], 14)
        self.assertEqual(report["experimental_bytes"], 27252072)
        self.assertEqual(report["final_test_opens"], 4)
        self.assertEqual(report["final_test_bytes"], 7783020)
        self.assertTrue(report["final_consumed"])
        self.assertEqual(json.loads((self.root / execution.FINAL_ACCESS_PATH).read_text())["fit_freeze_sha256"], digest)
        with self.assertRaises(execution.ExecutionContractError):
            reader.authorize_final(digest)

    def test_fit_freeze_wrong_parameters_fail_without_final_access(self):
        reader = self.arm()
        _, record = self.complete_training(reader)
        record = copy.deepcopy(record)
        record["parameters"]["n_estimators"] = 101
        payload = runner.evidence_bytes(record)
        (self.root / execution.FIT_PATH).write_bytes(payload)
        with self.assertRaisesRegex(execution.ExecutionContractError, "FIT_FREEZE_CONTRACT_FAILED"):
            reader.authorize_final(hashlib.sha256(payload).hexdigest())
        self.assertEqual(reader.report()["final_test_opens"], 0)
        self.assertFalse(reader.report()["final_consumed"])

    def test_fit_freeze_wrong_digest_fails_closed(self):
        reader = self.arm()
        self.complete_training(reader)
        with self.assertRaisesRegex(execution.ExecutionContractError, "FIT_FREEZE_HASH_MISMATCH"):
            reader.authorize_final("b" * 64)
        self.assertTrue(reader.report()["failed"])

    def test_final_hash_failure_is_consumed_and_no_other_final_is_read(self):
        reader = self.arm()
        digest, _ = self.complete_training(reader)
        reader.authorize_final(digest)
        final = [r for r in self.inventory if r["split"] == "FINAL_TEST"]
        self.write_source(final[0], bytes([88]) * final[0]["frame_bytes"])
        with self.assertRaisesRegex(execution.ExecutionContractError, "NATIVE_HASH_MISMATCH"):
            reader.read_native(final[0])
        self.assertTrue(reader.report()["final_consumed"])
        self.assertEqual(reader.report()["final_test_opens"], 1)
        with mock.patch.object(execution.os, "open") as opened:
            with self.assertRaises(execution.ExecutionContractError):
                reader.read_native(final[1])
            opened.assert_not_called()

    def test_final_wrong_size_consumes_open_without_claiming_bytes(self):
        reader = self.arm()
        digest, _ = self.complete_training(reader)
        reader.authorize_final(digest)
        final = next(r for r in self.inventory if r["split"] == "FINAL_TEST")
        self.write_source(final, b"synthetic")
        with self.assertRaisesRegex(execution.ExecutionContractError, "NATIVE_BYTE_COUNT_MISMATCH"):
            reader.read_native(final)
        report = reader.report()
        self.assertTrue(report["final_consumed"])
        self.assertEqual(report["final_test_opens"], 1)
        self.assertEqual(report["final_test_bytes"], 0)


class RunnerMetadataTests(unittest.TestCase):
    def proof(self):
        return {"head_sha": HEAD, "repository": runner.REPOSITORY, "runs": [
            {"head_sha": HEAD, "status": "completed", "conclusion": "success", "jobs": [
                {"name": name, "status": "completed", "conclusion": "success",
                 "steps": [{"name": "synthetic", "status": "completed", "conclusion": "success"}]}
                for name in runner.REQUIRED_JOBS]}]}

    def test_six_jobs_all_steps_success_at_exact_d1_required(self):
        runner.validate_ci(self.proof(), HEAD)
        for corrupt in ("head", "job", "step", "missing", "no-steps"):
            proof = self.proof()
            if corrupt == "head":
                proof["runs"][0]["head_sha"] = "2" * 40
            elif corrupt == "job":
                proof["runs"][0]["jobs"][0]["conclusion"] = "cancelled"
            elif corrupt == "step":
                proof["runs"][0]["jobs"][0]["steps"][0]["conclusion"] = "skipped"
            elif corrupt == "missing":
                proof["runs"][0]["jobs"].pop()
            else:
                proof["runs"][0]["jobs"][0]["steps"] = []
            with self.subTest(corrupt=corrupt), self.assertRaises(execution.ExecutionContractError):
                runner.validate_ci(proof, HEAD)

    def test_consumed_authority_denies_before_git_text_or_reader(self):
        with mock.patch.object(runner.os.path, "lexists", return_value=True), \
             mock.patch.object(runner, "_git") as git, mock.patch.object(runner, "_read_text") as read:
            with self.assertRaisesRegex(execution.ExecutionContractError, "TI3D_AUTHORITY_ALREADY_CONSUMED"):
                runner._preflight()
            git.assert_not_called()
            read.assert_not_called()

    def test_failed_preflight_never_arms_or_opens(self):
        written = {}
        with mock.patch.object(runner, "_preflight", side_effect=execution.ExecutionContractError("SYNTHETIC_DENIAL")), \
             mock.patch.object(runner.os.path, "lexists", return_value=False), \
             mock.patch.object(runner, "_write_once", side_effect=lambda n, v: written.update({n: v})), \
             mock.patch.object(runner, "arm_execution") as arm, mock.patch("builtins.print"):
            self.assertEqual(runner.main(), 3)
            arm.assert_not_called()
        self.assertEqual(written["results.json"]["SCIENTIFIC_FINAL_RUNS"], 0)
        self.assertEqual(written["results.json"]["experimental_bytes"], 0)

    def test_second_invocation_cannot_reclassify_consumed_final_as_sealed(self):
        with mock.patch.object(runner.os.path, "lexists", return_value=True), \
             mock.patch.object(runner, "_write_once") as write, \
             mock.patch.object(runner, "arm_execution") as arm, mock.patch("builtins.print") as printed:
            self.assertEqual(runner.main(), 3)
            write.assert_not_called()
            arm.assert_not_called()
            output = json.loads(printed.call_args.args[0])
            self.assertEqual(output["PRIOR_TERMINAL_AND_COUNTERS"], "PRESERVED_NOT_RECLASSIFIED")
            self.assertNotIn("ML_FINAL_TEST", output)
            self.assertNotIn("SCIENTIFIC_FINAL_RUNS", output)

    def test_feature_phase_requires_complete_patch_set(self):
        np = mock.Mock()
        with mock.patch.object(runner, "multimodal_features") as features:
            with self.assertRaisesRegex(execution.ExecutionContractError, "ALL_SUPPORT_REQUIRED_BEFORE_FEATURES"):
                runner.extract_features([], {}, {}, [], np, True)
            features.assert_not_called()

    def test_scientific_configuration_exact_types_and_frozen_rf(self):
        self.assertEqual(runner.EXPECTED_CONFIG["rf_parameters"], RF_PARAMETERS)
        wrong = copy.deepcopy(runner.EXPECTED_CONFIG)
        wrong["rf_parameters"]["min_impurity_decrease"] = 0
        self.assertFalse(execution.exact(wrong, runner.EXPECTED_CONFIG))
        self.assertEqual(runner.EXPECTED_CONFIG["performance_pass_floor"], None)
        self.assertFalse(runner.EXPECTED_AUTHORITY["cnn_authorized"])


class _Array:
    def __init__(self, values, dtype):
        self.values, self.dtype = list(values), dtype


class RunnerControlTests(unittest.TestCase):
    def setup_mocks(self, stack):
        manifest, _, inventory, serialized, active, _ = synthetic_inputs()
        training = [s for s in manifest["samples"] if s["split"] != "FINAL_TEST"]
        final = [s for s in manifest["samples"] if s["split"] == "FINAL_TEST"]
        reader, np, session = mock.Mock(), mock.Mock(), mock.Mock()
        np.int64 = "synthetic-int64"
        np.asarray.side_effect = lambda v, dtype: _Array(v, dtype)
        events, written, state = [], {}, {"final": False}
        counters = {"final_fit_calls": 0, "final_inference_calls": 0, "final_evaluations": 0}
        session.counters = counters
        def materialize(samples, inventory, reader, previous, records, is_final):
            events.append("support-final" if is_final else "support-training")
            state["final"] = is_final
            return {s["sample_id"]: "synthetic-patches" for s in samples}
        def features(samples, patches, previous, records, np, is_final):
            events.append("features-final" if is_final else "features-training")
            return "synthetic-feature-matrix"
        def fit(x, labels):
            self.assertIsInstance(labels, _Array)
            self.assertEqual(labels.dtype, np.int64)
            self.assertEqual(len(labels.values), 50)
            events.append("fit")
            counters["final_fit_calls"] += 1
            return {"final_fit_calls": 1, "synthetic": True}
        def freeze_fit(callback):
            events.append("freeze-fit")
            return callback({"final_fit_calls": 1, "synthetic": True})
        def authorize(digest):
            self.assertIn("fit-freeze.json", written)
            events.append("authorize-final")
        def infer(features, ids):
            events.append("infer-no-labels")
            counters["final_inference_calls"] += 1
            self.assertEqual(ids, [s["sample_id"] for s in final])
        def freeze_predictions(callback):
            events.append("freeze-predictions")
            return callback({"predictions": [{"sample_id": s["sample_id"], "predicted_label": 1,
                "probability_class_0": 0.2, "probability_class_1": 0.8} for s in final]})
        def score(labels, ids):
            self.assertIn("predictions.json", written)
            self.assertIsInstance(labels, _Array, "core requires ndarray, not a Python list")
            self.assertEqual(labels.dtype, np.int64)
            self.assertEqual(len(labels.values), 6)
            events.append("score")
            counters["final_evaluations"] += 1
            return {"balanced_accuracy": 0.5}
        def report():
            return {"experimental_opens": 14 if state["final"] else 10,
                    "experimental_bytes": 27252072 if state["final"] else 19469052,
                    "final_test_opens": 4 if state["final"] else 0,
                    "final_test_bytes": 7783020 if state["final"] else 0,
                    "final_consumed": state["final"], "entries": []}
        def write(name, value):
            self.assertNotIn(name, written)
            written[name] = value
            return hashlib.sha256(runner.evidence_bytes(value)).hexdigest()
        reader.report.side_effect = report
        reader.authorize_final.side_effect = authorize
        session.fit.side_effect = fit
        session.freeze_fit.side_effect = freeze_fit
        session.infer.side_effect = infer
        session.freeze_predictions.side_effect = freeze_predictions
        session.score.side_effect = score
        stack.enter_context(mock.patch.object(runner, "_preflight", return_value=(HEAD, manifest, serialized, inventory,
                           active, {}, training, final, np)))
        stack.enter_context(mock.patch.object(runner, "arm_execution", return_value=reader))
        stack.enter_context(mock.patch.object(runner, "FinalEvaluationSession", return_value=session))
        materializer = stack.enter_context(mock.patch.object(runner, "materialize_patches", side_effect=materialize))
        extractor = stack.enter_context(mock.patch.object(runner, "extract_features", side_effect=features))
        writer = stack.enter_context(mock.patch.object(runner, "_write_once", side_effect=write))
        stack.enter_context(mock.patch("builtins.print"))
        return reader, session, materializer, extractor, writer, events, written

    def test_complete_prediction_first_order_and_typed_labels_after_freeze(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            reader, session, _, _, _, events, written = self.setup_mocks(stack)
            self.assertEqual(runner.main(), 0)
            self.assertEqual(events, ["support-training", "features-training", "fit", "freeze-fit", "authorize-final",
                "support-final", "features-final", "infer-no-labels", "freeze-predictions", "score"])
            session.fit.assert_called_once()
            session.infer.assert_called_once()
            session.score.assert_called_once()
            reader.close.assert_called_once()
        self.assertEqual(written["results.json"]["FINAL_EVALUATIONS"], 1)
        self.assertTrue(written["results.json"]["ML_FINAL_TEST_EXECUTED"])
        self.assertNotIn("true_labels", written["predictions.json"])

    def test_training_support_failure_prevents_features_fit_and_final(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            _, session, materializer, extractor, _, _, written = self.setup_mocks(stack)
            materializer.side_effect = execution.ExecutionContractError("SYNTHETIC_TRAINING_SUPPORT")
            self.assertEqual(runner.main(), 2)
            extractor.assert_not_called()
            session.fit.assert_not_called()
            session.infer.assert_not_called()
            materializer.assert_called_once()
        self.assertEqual(written["results.json"]["FINAL_FIT_CALLS"], 0)

    def test_fit_prevalidation_failure_does_not_count_unperformed_fit(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            reader, session, materializer, _, _, _, written = self.setup_mocks(stack)
            session.fit.side_effect = execution.ExecutionContractError("SYNTHETIC_BEFORE_FIT")
            self.assertEqual(runner.main(), 2)
            reader.authorize_final.assert_not_called()
            materializer.assert_called_once()
        self.assertEqual(written["results.json"]["FINAL_FIT_CALLS"], 0)
        self.assertEqual(written["results.json"]["FINAL_FIT_STARTED"], 1)

    def test_fit_freeze_failure_never_opens_final(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            reader, session, materializer, _, _, _, written = self.setup_mocks(stack)
            session.freeze_fit.side_effect = OSError("synthetic durability failure")
            self.assertEqual(runner.main(), 2)
            reader.authorize_final.assert_not_called()
            materializer.assert_called_once()
        self.assertEqual(written["results.json"]["ML_FINAL_TEST"], "SEALED_WITH_HISTORICAL_NON_ML_EXPOSURE")

    def test_final_support_failure_consumes_without_features_or_partial_inference(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            _, session, materializer, extractor, _, _, written = self.setup_mocks(stack)
            original = materializer.side_effect
            def fail_final(*args):
                original(*args)
                if args[-1]:
                    raise execution.ExecutionContractError("SYNTHETIC_FINAL_SUPPORT")
                return {s["sample_id"]: "synthetic" for s in args[0]}
            materializer.side_effect = fail_final
            self.assertEqual(runner.main(), 2)
            extractor.assert_called_once()
            session.infer.assert_not_called()
            session.score.assert_not_called()
            self.assertEqual(materializer.call_count, 2)
        result = written["results.json"]
        self.assertEqual(result["ML_FINAL_TEST"], "CONSUMED")
        self.assertEqual(result["TI3_D_FINAL"], "BLOCKED_FINAL_SUPPORT_OR_INTEGRITY")
        self.assertFalse(result["ML_FINAL_TEST_EXECUTED"])

    def test_prediction_freeze_failure_denies_scoring_and_retry(self):
        from contextlib import ExitStack
        with ExitStack() as stack:
            _, session, _, _, _, _, written = self.setup_mocks(stack)
            session.freeze_predictions.side_effect = OSError("synthetic prediction write failure")
            self.assertEqual(runner.main(), 2)
            session.fit.assert_called_once()
            session.infer.assert_called_once()
            session.score.assert_not_called()
        self.assertEqual(written["results.json"]["FINAL_EVALUATIONS"], 0)
        self.assertEqual(written["results.json"]["ML_FINAL_TEST"], "CONSUMED")

    def test_one_support_phase_before_all_feature_processing(self):
        np = mock.Mock()
        reader = mock.Mock()
        samples = [{"sample_id": str(i), "split": "FINAL_TEST", "source_id": "ESM1", "frame_index": 293}
                   for i in range(6)]
        images = [{"source_id": "ESM1", "frame_index": 293}, {"source_id": "ESM2", "frame_index": 293}]
        with mock.patch.object(runner, "checked_luminance", side_effect=ValueError("synthetic support")), \
             mock.patch.object(runner, "multimodal_features") as feature:
            with self.assertRaises(ValueError):
                runner.materialize_patches(samples, images, reader, {}, [], True)
            feature.assert_not_called()
            reader.read_native.assert_called_once()


if __name__ == "__main__":
    unittest.main()
